// AWS HealthOmics Nextflow Configuration
// Generated by CWL to Nextflow Migration Toolkit

// AWS HealthOmics specific configuration
aws {
    region = 'us-east-1'
    batch {
        cliPath = '/home/ec2-user/miniconda/bin/aws'
        maxParallelTransfers = 3
        maxTransferAttempts = 1
        delayBetweenAttempts = '30 sec'
    }
}

// HealthOmics configuration
healthomics {
    enabled = true
    region = 'us-east-1'
    batch {
        maxParallelTransfers = 3
        maxTransferAttempts = 1
        delayBetweenAttempts = '30 sec'
    }
}

// Process configuration
process {
    // Default resource allocation
    cpus = 1
    memory = '1 GB'
    time = '1h'
    
    // Error handling
    errorStrategy = 'terminate'
    
    // Container configuration
    container = 'public.ecr.aws/healthomics/example:latest'
    
    // AWS HealthOmics specific settings
    {% if aws_healthomics %}
    executor = 'awsbatch'
    queue = 'healthomics-queue'
    
    // Resource allocation based on mapping
    {% for process_name, resources in resource_mapping.items() %}
    withName: {{ process_name }} {
        cpus = {{ resources.get('cpus', 1) }}
        memory = '{{ resources.get('memory', '1 GB') }}'
        time = '{{ resources.get('time', '1h') }}'
    }
    {% endfor %}
    {% endif %}
}

// Execution profiles
profiles {
    healthomics {
        process.executor = 'awsbatch'
        process.queue = 'healthomics-queue'
        aws.region = 'us-east-1'
    }
    
    healthomics-dev {
        process.executor = 'awsbatch'
        process.queue = 'healthomics-dev-queue'
        aws.region = 'us-east-1'
    }
    
    healthomics-prod {
        process.executor = 'awsbatch'
        process.queue = 'healthomics-prod-queue'
        aws.region = 'us-east-1'
    }
}

// Workflow metadata
workflow {
    name = '{{ workflow_info.name }}'
    {% if workflow_info.description %}
    description = '{{ workflow_info.description }}'
    {% endif %}
}
