// Base Nextflow Configuration
// Generated by CWL to Nextflow Migration Toolkit

// Process configuration
process {
    // Default resource allocation
    cpus = 1
    memory = '1 GB'
    time = '1h'
    
    // Error handling
    errorStrategy = 'terminate'
    
    // Container configuration
    container = 'ubuntu:latest'
    
    // Resource allocation based on mapping
    {% for process_name, resources in resource_mapping.items() %}
    withName: {{ process_name }} {
        cpus = {{ resources.get('cpus', 1) }}
        memory = '{{ resources.get('memory', '1 GB') }}'
        time = '{{ resources.get('time', '1h') }}'
    }
    {% endfor %}
}

// Execution profiles
profiles {
    local {
        process.executor = 'local'
    }
    
    slurm {
        process.executor = 'slurm'
        process.queue = 'default'
    }
    
    sge {
        process.executor = 'sge'
        process.queue = 'default'
    }
}

// Workflow metadata
workflow {
    name = '{{ workflow_info.name }}'
    {% if workflow_info.description %}
    description = '{{ workflow_info.description }}'
    {% endif %}
}
